import { ModuleManifest } from '@jaago/module-system';

export const adminProcurementManifest: ModuleManifest = {
  key: 'admin_procurement',
  name: 'Admin & Procurement',
  version: '1.0.0',
  summary: 'Enterprise Admin, Procurement & Supply Chain Management for JAAGO Foundation',
  description: 'Procurement requisitions, vendor catalog, purchase orders, quotations, goods receipt, asset tracking, inventory, and fiscal budgeting.',
  category: 'operations',
  author: 'JAAGO Foundation Engineering',
  minCoreVersion: '2.2.0',
  depends: [],
  permissions: [
    {
      key: 'procurement.view',
      name: 'View Procurement',
      description: 'Access the procurement dashboard, orders, and logs',
      category: 'procurement',
    },
    {
      key: 'procurement.manage',
      name: 'Manage Procurement',
      description: 'Create purchase requisitions, orders, and approve expenditures',
      category: 'procurement',
    },
    {
      key: 'procurement.vendors',
      name: 'Manage Vendors & Suppliers',
      description: 'Create, update, import, and review supplier master list',
      category: 'procurement',
    },
    {
      key: 'procurement.settings',
      name: 'Procurement Configuration',
      description: 'Configure approval tiers, numbering prefixes, and fiscal thresholds',
      category: 'procurement',
    },
  ],
  models: [
    'procurement_requests',
    'purchase_orders',
    'procurement_vendors',
    'quotations_rfqs',
    'goods_receipts',
    'inventory_items',
    'procurement_assets',
    'procurement_categories',
    'procurement_units',
    'procurement_warehouses',
    'procurement_contracts',
    'procurement_budgets',
    'procurement_settings',
  ],
  events: {
    produces: [
      'procurement.po.created',
      'procurement.po.approved',
      'procurement.pr.submitted',
      'procurement.vendor.onboarded',
    ],
    consumes: ['user.created', 'organization.updated'],
  },
  navigation: [
    {
      key: 'procurement_dashboard',
      label: 'Procurement Dashboard',
      icon: 'ShoppingCart',
      path: '/admin-procurement',
      order: 20,
      permission: 'procurement.view',
    },
    {
      key: 'procurement_purchase_requisitions',
      label: 'Purchase Requisition',
      icon: 'FileText',
      path: '/admin-procurement/requests',
      order: 21,
      permission: 'procurement.view',
    },
    {
      key: 'procurement_general_requisitions',
      label: 'General Requisition',
      icon: 'ClipboardList',
      path: '/admin-procurement/general-requisitions',
      order: 22,
      permission: 'procurement.view',
    },
    {
      key: 'procurement_orders',
      label: 'Purchase Orders',
      icon: 'Package',
      path: '/admin-procurement/orders',
      order: 23,
      permission: 'procurement.view',
    },
    {
      key: 'procurement_vendors',
      label: 'Vendors & Suppliers',
      icon: 'Users',
      path: '/admin-procurement/vendors',
      order: 23,
      permission: 'procurement.vendors',
    },
    {
      key: 'procurement_settings',
      label: 'Procurement Settings',
      icon: 'Settings',
      path: '/admin-procurement/settings',
      order: 30,
      permission: 'procurement.settings',
    },
  ],
  autoInstall: true,
};
