import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(process.cwd(), 'apps/web/.env.local') });
dotenv.config({ path: path.resolve(process.cwd(), '.env') });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY || '';

const supabaseAdmin = createClient(supabaseUrl, serviceRoleKey);

const SEED_EMPLOYEES = [
  {
    code: 'EMP-NASIF-001',
    name: 'Nasif Kamal',
    designation: 'Coordinator, Tech 4 Development',
    work_email: 'nasif.kamal@jaago.com.bd',
    work_mobile: '+880 1711 000001',
    working_schedule: 'General Schedule (10:00 AM - 6:00 PM)',
    status: 'Active',
    organization: 'JAAGO Foundation Trust',
    branch: 'Head Office (Banani)',
    department: "Founder's Office / FC",
    project: 'Tech 4 Development',
    supervisor: 'Founder & Executive Director',
    secondary_supervisor: 'Habibur Rahman',
    work_location: 'Banani, Dhaka',
    remark: 'Lead Developer & System Administrator',
    personal_email: 'nasif.personal@gmail.com',
    personal_phone: '+880 1811 000001',
    bank_name: 'Eastern Bank Ltd',
    bank_account_number: '1041234567800',
    nick_name: 'Nasif',
    nid: '1996269123456789',
    blood_group: 'B+',
    birthday: '1996-05-15',
    gender: 'MALE',
    religion: 'Islam',
    marital_status: 'Single',
    emergency_contact_name: 'Kamal Hossain (Father)',
    emergency_phone: '+880 1811 999000',
    nationality: 'Bangladeshi',
    passport_no: 'A09876543',
    home_address: 'Road 11, Banani, Dhaka-1213',
    dependent_children: 0,
    joining_date: '2026-08-24',
    contract_end_date: '2028-12-31',
    wage_type: 'Fixed',
    wage: 150000,
    salary_jul_dec: 150000,
    salary_jan_jun: 150000,
    monthly_total_allowance: 'Yes',
    six_months_completion_status: 'Yes',
    probationary_status: 'Confirmed',
    contract_type: 'Full Time',
    no_tax_deduction: false,
    bonus_eligibility: 'Yes',
    pf_applies: 'Yes',
    pf_rate: 10,
    regular_salary: 150000,
    total_current_salary: 150000,
    currency: 'BDT',
    office_days: 'Sunday to Thursday',
    office_hours: '10:00 AM - 06:00 PM',
    rfid: 'RFID-100290',
    leave_group: 'Standard Full-time',
    employee_type: 'Permanent',
    is_user: true,
  },
  {
    code: 'GLSP08241107940',
    name: 'Abdul Aziz',
    designation: 'Security Guard',
    work_email: 'abdul.aziz@jaago.com.bd',
    work_mobile: '+880 1711 000001',
    working_schedule: 'General 9 AM to 5 PM',
    status: 'Active',
    organization: 'JAAGO Foundation Trust',
    branch: 'Head Office (Banani)',
    department: 'Program Implementation',
    project: 'Campus Security',
    supervisor: 'Nasif Kamal',
    secondary_supervisor: 'Habibur Rahman',
    work_location: 'Banani, Dhaka',
    remark: 'Night shift rotation assigned',
    personal_email: 'aziz.private@gmail.com',
    personal_phone: '+880 1811 000001',
    bank_name: 'Eastern Bank Ltd',
    bank_account_number: '1041234567801',
    nick_name: 'Aziz',
    nid: '1988269123450001',
    blood_group: 'B+',
    birthday: '1988-04-12',
    gender: 'MALE',
    religion: 'Islam',
    marital_status: 'Married',
    emergency_contact_name: 'Fatema Begum (Spouse)',
    emergency_phone: '+880 1811 999001',
    nationality: 'Bangladeshi',
    passport_no: 'A01928371',
    home_address: 'Mohakhali TB Gate, Dhaka-1212',
    dependent_children: 2,
    joining_date: '2024-05-12',
    contract_end_date: '2027-05-11',
    wage_type: 'Fixed',
    wage: 25000,
    salary_jul_dec: 25000,
    salary_jan_jun: 25000,
    monthly_total_allowance: 'Yes',
    six_months_completion_status: 'Yes',
    probationary_status: 'Confirmed',
    contract_type: 'Full Time',
    no_tax_deduction: false,
    bonus_eligibility: 'Yes',
    pf_applies: 'Yes',
    pf_rate: 10,
    regular_salary: 25000,
    total_current_salary: 27000,
    currency: 'BDT',
    office_days: 'Sunday to Thursday',
    office_hours: '09:00 AM - 05:00 PM',
    rfid: 'RFID-100291',
    leave_group: 'Standard Full-time',
    employee_type: 'Permanent',
    is_user: false,
  },
  {
    code: 'ADM011420100045',
    name: 'Abdul Mazid',
    designation: 'Manager',
    work_email: 'abdul.mazid@jaago.com.bd',
    work_mobile: '+880 1711 000002',
    working_schedule: 'General 9 AM to 5 PM',
    status: 'Active',
    organization: 'JAAGO Foundation',
    branch: 'Head Office (Banani)',
    department: 'Digital School Program',
    project: 'Telco Digital School',
    supervisor: 'Nasif Kamal',
    secondary_supervisor: 'Farhana Ahmed',
    work_location: 'Banani, Dhaka',
    remark: 'Leads DSP Operations across 12 branch schools',
    personal_email: 'mazid.p@gmail.com',
    personal_phone: '+880 1811 000002',
    bank_name: 'BRAC Bank Ltd',
    bank_account_number: '1501234567802',
    nick_name: 'Mazid',
    nid: '1985269123450002',
    blood_group: 'O+',
    birthday: '1985-08-20',
    gender: 'MALE',
    religion: 'Islam',
    marital_status: 'Married',
    emergency_contact_name: 'Nasrin Akhter (Spouse)',
    emergency_phone: '+880 1811 999002',
    nationality: 'Bangladeshi',
    passport_no: 'B02938472',
    home_address: 'Gulshan 2, Dhaka',
    dependent_children: 1,
    joining_date: '2021-03-01',
    contract_end_date: '2026-03-01',
    wage_type: 'Fixed',
    wage: 95000,
    salary_jul_dec: 95000,
    salary_jan_jun: 95000,
    monthly_total_allowance: 'Yes',
    six_months_completion_status: 'Yes',
    probationary_status: 'Confirmed',
    contract_type: 'Full Time',
    no_tax_deduction: false,
    bonus_eligibility: 'Yes',
    pf_applies: 'Yes',
    pf_rate: 10,
    regular_salary: 95000,
    total_current_salary: 95000,
    currency: 'BDT',
    office_days: 'Sunday to Thursday',
    office_hours: '09:00 AM - 05:00 PM',
    rfid: 'RFID-100292',
    leave_group: 'Standard Full-time',
    employee_type: 'Permanent',
    is_user: false,
  },
  {
    code: 'DC082224020391',
    name: 'Abdullah Al Imran',
    designation: 'Assistant Manager',
    work_email: 'abdullah.imran@jaago.com.bd',
    work_mobile: '+880 1711 000003',
    working_schedule: 'General Schedule (10:00 AM - 6:00 PM)',
    status: 'Active',
    organization: 'JAAGO Foundation',
    branch: 'Head Office (Banani)',
    department: 'Communications',
    project: 'Digital Media & Storytelling',
    supervisor: 'Farhana Ahmed',
    secondary_supervisor: 'Nasif Kamal',
    work_location: 'Banani, Dhaka',
    remark: 'Key contact for external campaigns',
    personal_email: 'imran.comm@gmail.com',
    personal_phone: '+880 1811 000003',
    bank_name: 'City Bank Ltd',
    bank_account_number: '2201234567803',
    nick_name: 'Imran',
    nid: '1992269123450003',
    blood_group: 'A+',
    birthday: '1992-11-14',
    gender: 'MALE',
    religion: 'Islam',
    marital_status: 'Single',
    emergency_contact_name: 'Rashidul Hasan (Brother)',
    emergency_phone: '+880 1811 999003',
    nationality: 'Bangladeshi',
    passport_no: 'C03948573',
    home_address: 'Mirpur DOHS, Dhaka',
    dependent_children: 0,
    joining_date: '2022-08-16',
    contract_end_date: '2027-08-15',
    wage_type: 'Fixed',
    wage: 75000,
    salary_jul_dec: 75000,
    salary_jan_jun: 75000,
    monthly_total_allowance: 'Yes',
    six_months_completion_status: 'Yes',
    probationary_status: 'Confirmed',
    contract_type: 'Full Time',
    no_tax_deduction: false,
    bonus_eligibility: 'Yes',
    pf_applies: 'Yes',
    pf_rate: 10,
    regular_salary: 75000,
    total_current_salary: 75000,
    currency: 'BDT',
    office_days: 'Sunday to Thursday',
    office_hours: '10:00 AM - 06:00 PM',
    rfid: 'RFID-100293',
    leave_group: 'Standard Full-time',
    employee_type: 'Permanent',
    is_user: false,
  },
  {
    code: 'EMK2025154',
    name: 'Abdullah Al Yousuf',
    designation: 'Program Officer',
    work_email: 'abdullah.yousuf@emkcenter.org',
    work_mobile: '+880 1711 000004',
    working_schedule: 'General Schedule (10:00 AM - 6:00 PM)',
    status: 'Active',
    organization: 'JAAGO Foundation',
    branch: 'Head Office (Banani)',
    department: 'EMK Center',
    project: 'EMK Youth Innovation Labs',
    supervisor: 'Farhana Ahmed',
    secondary_supervisor: 'Nasif Kamal',
    work_location: 'Dhanmondi, Dhaka',
    remark: 'Coordinator for US Embassy partnership programs',
    personal_email: 'yousuf.emk@gmail.com',
    personal_phone: '+880 1811 000004',
    bank_name: 'Eastern Bank Ltd',
    bank_account_number: '1041234567804',
    nick_name: 'Yousuf',
    nid: '1995269123450004',
    blood_group: 'AB+',
    birthday: '1995-02-18',
    gender: 'MALE',
    religion: 'Islam',
    marital_status: 'Single',
    emergency_contact_name: 'Jahanara Yousuf (Mother)',
    emergency_phone: '+880 1811 999004',
    nationality: 'Bangladeshi',
    passport_no: 'D04958674',
    home_address: 'Dhanmondi 27, Dhaka',
    dependent_children: 0,
    joining_date: '2025-02-24',
    contract_end_date: '2026-02-23',
    wage_type: 'Fixed',
    wage: 55000,
    salary_jul_dec: 55000,
    salary_jan_jun: 55000,
    monthly_total_allowance: 'Yes',
    six_months_completion_status: 'No',
    probationary_status: 'On Probation',
    contract_type: 'Full Time',
    no_tax_deduction: false,
    bonus_eligibility: 'No',
    pf_applies: 'No',
    pf_rate: 0,
    regular_salary: 55000,
    total_current_salary: 55000,
    currency: 'BDT',
    office_days: 'Sunday to Thursday',
    office_hours: '10:00 AM - 06:00 PM',
    rfid: 'RFID-100294',
    leave_group: 'Project Staff',
    employee_type: 'Contractual',
    is_user: false,
  },
];

async function seed() {
  console.log('Seeding employees into Supabase...');
  for (const emp of SEED_EMPLOYEES) {
    const { data, error } = await supabaseAdmin
      .from('employees')
      .upsert(emp, { onConflict: 'code' })
      .select();

    if (error) {
      console.error(`Error saving ${emp.name}:`, error.message);
    } else {
      console.log(`✓ Seeded ${emp.name} (${emp.code})`);
    }
  }

  const { data: countData } = await supabaseAdmin.from('employees').select('id, name, code, work_email');
  console.log('\nTotal employees in Supabase now:', countData?.length);
  console.log(countData);
}

seed().catch(console.error);
