import {
  exportEmployeesToComprehensiveCSV,
  parseComprehensiveEmployeeCSV,
  EMPLOYEE_CSV_COLUMNS,
} from '../../apps/web/lib/employee-csv-helper';
import type { FullEmployeeProfile } from '../../apps/web/components/pnc/employee-profile-detail';

console.log('---------------------------------------------------------');
console.log('TOTAL REGISTERED CSV FIELDS:', EMPLOYEE_CSV_COLUMNS.length);
console.log('---------------------------------------------------------');

const sampleEmployee: FullEmployeeProfile = {
  id: 'test-1',
  name: 'Nasif Kamal',
  code: 'FO032507061190',
  avatarUrl: '',
  designation: 'Coordinator, Technology',
  workEmail: 'nasif.kamal@jaago.com.bd',
  workMobile: '+8801780522666',
  status: 'Active',
  isArchived: false,
  workingSchedule: 'JAAGO HQ (10:00 AM - 06:00 PM)',
  organization: 'JAAGO Foundation',
  branch: 'Head Office (Banani)',
  department: "Founder's Office",
  project: 'General Operations',
  team: 'Executive Technology Team',
  supervisor: 'Founder',
  secondarySupervisor: 'Director',
  workLocation: 'Banani, Dhaka',
  remark: 'Lead Architect',
  nickName: 'Nasif',
  nid: '19952691234567890',
  passportNo: 'A01234567',
  birthday: '1995-08-15',
  gender: 'MALE',
  bloodGroup: 'B+',
  religion: 'Islam',
  maritalStatus: 'Single',
  nationality: 'Bangladeshi',
  personalEmail: 'nasif@gmail.com',
  personalPhone: '+8801780522666',
  homeAddress: 'Uttara, Dhaka',
  emergencyContactName: 'Kamal',
  emergencyPhone: '+8801711223344',
  dependentChildren: 0,
  bankName: 'BRAC Bank',
  bankAccountNumber: '1501203456789001',
  joiningDate: '2024-08-26',
  contractEndDate: '2027-08-25',
  wageType: 'Fixed',
  wage: 65000,
  salaryJulDec: 65000,
  salaryJanJun: 65000,
  currency: 'BDT',
  monthlyTotalAllowance: 'Yes',
  bonusEligibility: 'Yes',
  pfApplies: 'Yes',
  pfRate: 10,
  noTaxDeduction: false,
  sixMonthsCompletionStatus: 'Yes',
  probationaryStatus: 'Confirmed',
  contractType: 'Full Time',
  regularSalary: 65000,
  extraHours: 0,
  extraPayment: 0,
  calculationValue: '1.0x',
  temporarySalary: 0,
  totalCurrentSalary: 65000,
  adjustmentStartDate: '2024-08-26',
  adjustmentEndDate: '2027-08-25',
  assignedTeacherStaff: 'Staff',
  payrollRemark: 'Executive',
  insuranceStatus: 'Active',
  insuranceCoverageCategory: 'Executive Plan A',
  insuranceMonthlyPremium: 2500,
  employeeHealthInsuranceId: 'INS-001',
  spouseName: '',
  spouseHealthInsuranceId: '',
  child1Name: '',
  child1HealthInsuranceId: '',
  child2Name: '',
  child2HealthInsuranceId: '',
  child3Name: '',
  child3HealthInsuranceId: '',
  employeeType: 'Permanent',
  officeDays: 'Sunday to Thursday',
  officeHours: '10:00 AM - 06:00 PM',
  rfid: 'RFID-001',
  leaveGroup: 'Executive Full-time',
  leavePolicy: 'Standard Executive Employee Policy',
  casualLeaveAllocated: 14,
  casualLeaveUsed: 2,
  sickLeaveAllocated: 10,
  sickLeaveUsed: 1,
  earnedLeaveAllocated: 15,
  earnedLeaveUsed: 0,
  specialLeaveAllocated: 5,
  specialLeaveUsed: 0,
  weekendDays: 'Friday, Saturday',
  overtimeEligible: 'No',
  attendanceGracePeriodMin: 15,
  logHistory: [],
  isUser: true,
  userId: 'usr-1',
};

const csv = exportEmployeesToComprehensiveCSV([sampleEmployee]);
console.log('GENERATED CSV HEADERS & ROWS:');
console.log(csv.slice(0, 300) + '...');

const parseResult = parseComprehensiveEmployeeCSV(csv);
console.log('PARSED STATUS:', parseResult.success);
console.log('PARSED COUNT:', parseResult.employees.length);
console.log('SAMPLE PARSED EMPLOYEE:');
console.log({
  name: parseResult.employees[0]?.name,
  code: parseResult.employees[0]?.code,
  wage: parseResult.employees[0]?.wage,
  rfid: parseResult.employees[0]?.rfid,
  leavePolicy: parseResult.employees[0]?.leavePolicy,
  insuranceCoverageCategory: parseResult.employees[0]?.insuranceCoverageCategory,
});
console.log('PARSING ERRORS (Expected: 0):', parseResult.errors.length);
