export const ErrorCode = {
  // ── AUTH & SECURITY ──
  AUTH_UNAUTHENTICATED: 'AUTH_UNAUTHENTICATED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  AUTH_MFA_REQUIRED: 'AUTH_MFA_REQUIRED',
  AUTH_MFA_INVALID: 'AUTH_MFA_INVALID',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',

  // ── AUTHORIZATION & RBAC ──
  AUTHZ_INSUFFICIENT_PERMISSIONS: 'AUTHZ_INSUFFICIENT_PERMISSIONS',
  AUTHZ_TENANT_VIOLATION: 'AUTHZ_TENANT_VIOLATION',
  AUTHZ_ROLE_NOT_FOUND: 'AUTHZ_ROLE_NOT_FOUND',

  // ── VALIDATION & BAD REQUEST ──
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  BAD_REQUEST: 'BAD_REQUEST',
  INVALID_CURSOR: 'INVALID_CURSOR',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',

  // ── MODULE SYSTEM ──
  MODULE_NOT_FOUND: 'MODULE_NOT_FOUND',
  MODULE_ALREADY_INSTALLED: 'MODULE_ALREADY_INSTALLED',
  MODULE_DEPENDENCY_MISSING: 'MODULE_DEPENDENCY_MISSING',
  MODULE_DEPENDENCY_CYCLE: 'MODULE_DEPENDENCY_CYCLE',
  MODULE_CANNOT_DISABLE_DEPENDENCY: 'MODULE_CANNOT_DISABLE_DEPENDENCY',
  MODULE_MIGRATION_FAILED: 'MODULE_MIGRATION_FAILED',
  MODULE_DISABLED: 'MODULE_DISABLED',

  // ── BUSINESS DOMAINS ──
  FINANCE_INVOICE_NOT_APPROVABLE: 'FINANCE_INVOICE_NOT_APPROVABLE',
  FINANCE_JOURNAL_UNBALANCED: 'FINANCE_JOURNAL_UNBALANCED',
  HR_EMPLOYEE_NOT_FOUND: 'HR_EMPLOYEE_NOT_FOUND',
  WORKFLOW_INVALID_TRANSITION: 'WORKFLOW_INVALID_TRANSITION',

  // ── STORAGE & FILES ──
  STORAGE_FILE_NOT_FOUND: 'STORAGE_FILE_NOT_FOUND',
  STORAGE_MALWARE_DETECTED: 'STORAGE_MALWARE_DETECTED',
  STORAGE_INVALID_MIME_TYPE: 'STORAGE_INVALID_MIME_TYPE',

  // ── PROXY & NETWORK ──
  PROXY_PATH_NOT_ALLOWED: 'PROXY_PATH_NOT_ALLOWED',
  UPSTREAM_UNAVAILABLE: 'UPSTREAM_UNAVAILABLE',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // ── SYSTEM & INFRASTRUCTURE ──
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  DATABASE_ERROR: 'DATABASE_ERROR',
  REDIS_ERROR: 'REDIS_ERROR',
  CONFIG_ERROR: 'CONFIG_ERROR',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
